export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';

export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";

export const GRAPHCOOL_AUTH_TOKEN_OBTAINED = "GRAPHCOOL_AUTH_TOKEN_OBTAINED";
export const GRAPHCOOL_AUTH_TOKEN_ERROR = "GRAPHCOOL_AUTH_TOKEN_ERROR";
export const GRAPHCOOL_AUTH_TOKEN_CLEAR = "GRAPHCOOL_AUTH_TOKEN_CLEAR";

export const SET_USER_ID = "SET_USER_ID";
export const CLEAR_USER_ID = "CLEAR_USER_ID";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_LOADED = "USER_DETAILS_LOADED";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";

export const SAVE_PRESCP_LOADING = "SAVE_PRESCP_LOADING";
export const SAVE_PRESCP_LOADED = "SAVE_PRESCP_LOADED";
export const SAVE_PRESCP_ERROR = "SAVE_PRESCP_ERROR";
export const CLEAR_PRESCP = "CLEAR_PRESCP";

export const SET_PROFILE_URL = "SET_PROFILE_URL";
export const CLEAR_PROFILE_URL = "CLEAR_PROFILE_URL";
export const UPLOADING_PROFILE_PIC = "UPLOADING_PROFILE_PIC";
export const UPLOADED_PROFILE_PIC = "UPLOADED_PROFILE_PIC";
export const ERROR_UPLOADING_PROFILE_PIC = "ERROR_UPLOADING_PROFILE_PIC";

export const SET_PRESCRIPTION_URL = "SET_PRESCRIPTION_URL";
export const CLEAR_PRESCRIPTION_URL = "CLEAR_PRESCRIPTION_URL";
export const UPLOADING_PRESCRIPTION = "UPLOADING_PRESCRIPTION_IMAGE";
export const UPLOADED_PRESCRIPTION = "UPLOADED_PRESCRIPTION_IMAGE";
export const ERROR_UPLOADING_PRESCRIPTION = "ERROR_UPLOADING_PRESCRIPTION";
// export const CLEAR_PRESCRIPTION_STATUS = "CLEAR_PRESCRIPTION_STATUS";