export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';

export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";

export const GRAPHCOOL_AUTH_TOKEN_OBTAINED = "GRAPHCOOL_AUTH_TOKEN_OBTAINED";
export const GRAPHCOOL_AUTH_TOKEN_ERROR = "GRAPHCOOL_AUTH_TOKEN_ERROR";
export const GRAPHCOOL_AUTH_TOKEN_CLEAR = "GRAPHCOOL_AUTH_TOKEN_CLEAR";

export const SET_USER_ID = "SET_USER_ID";
export const CLEAR_USER_ID = "CLEAR_USER_ID";
